version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "anthonymckie"
    assignees:
      - "anthonymckie"
    commit-message:
      prefix: "bundler"
      include: "scope"
    labels:
      - "dependencies"
      - "bundler"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "anthonymckie"
    commit-message:
      prefix: "github-actions"
    labels:
      - "dependencies"
      - "github-actions"