name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false  # Disable cache to avoid conflicts
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        rm -f Gemfile.lock  # Remove lock file to avoid conflicts
        bundle install --retry 3
      
    - name: Build site
      run: |
        bundle exec jekyll build --verbose
        
    - name: Run HTMLProofer
      run: |
        bundle exec htmlproofer ./_site \
          --disable-external \
          --check-html \
          --allow-hash-href \
          --empty-alt-ignore
      continue-on-error: true  # Don't fail build on minor HTML issues
        
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Install dependencies and run security audit
      run: |
        gem install bundler bundler-audit
        rm -f Gemfile.lock
        bundle install --retry 3
        bundle audit --update
      continue-on-error: true  # Don't fail on security issues (they'll be fixed by Dependabot)